#include <ReleaseNotesExcerpt.h>
#include <gtest/gtest.h>

#include <string>

namespace {

// The openings of three real release bodies, as GitHub serves them: two written in the web
// editor (CRLF), one generated by a script (LF, a heading first).
const std::string NOTES_2_37 =
    "2.37 improves reading position recovery, chapter page counting, reading statistics, keyboard layouts, and "
    "several navigation issues.\r\n\r\n## Highlights\r\n\r\n- Reading position is now restored correctly after "
    "layout changes.\r\n- Chapter page counts work across multi-file chapters.\r\n- Leaving a book is much faster, "
    "even with large reading histories.\r\n- Reading statistics can be removed per book.\r\n- Added Cyr";
const std::string NOTES_2_36 =
    "A couple of minor fixes reported, most annoying probably the X4 ghosting on the settings screen\r\n\r\n## "
    "What's Changed\r\n* fix(home): refresh recent-book metadata when its .opf sidecar changes by @jpirnay in "
    "https://github.com/jpirnay/witchhunt-reader/pull/331\r\n* fix(browser): label and trim the firmware picker's "
    "Options menu by @jpirnay in https://github.com/jpirnay/witchhunt-reader/pull/332\r\n* fix(nav): front Up wraps "
    "from the first row of a list that opens with a header by @jpirnay in "
    "https://github.com/jpirnay/witchhunt-reader/pull/334\r\n* fix(display): seed RED RAM before every swi";
const std::string NOTES_2_35 =
    "# CrossPoint 2.35.0-rc.1\n\nChanges since `2.31` (`ed9b24d`) through `f046aa7`.\n\n## User-Facing "
    "Changes\n\n- fix: bound the per-chapter style memos -- a PDF-derived chapter has one unique inline style per "
    "word (`703905f`)\n- fix: stop rendering text that CSS makes invisible -- transparent colour, opacity 0, "
    "visibility hidden (`f6e7dde`)\n- docs: record the displayWindow capability gap and framebuffer baseline "
    "findings (`90ff639`)\n- fix: keep text inside its box at the large UI font size (`3fa1647`)\n- fix: draw the "
    "status bar full";

std::string excerptOf(const std::string& body, bool complete = true, size_t outSize = 512, size_t maxLines = 4) {
  std::string out(outSize, '\x7f');
  const size_t n = release_notes::excerpt(body.data(), body.size(), complete, out.data(), outSize, maxLines);
  EXPECT_LT(n, outSize);
  EXPECT_EQ(out[n], '\0');
  return out.substr(0, n);
}

TEST(ReleaseNotesExcerpt, TheWebEditorsCrlfNotesKeepTheirOpeningLines) {
  EXPECT_EQ(excerptOf(NOTES_2_37, false),
            "2.37 improves reading position recovery, chapter page counting, reading statistics, keyboard layouts, "
            "and several navigation issues.\n"
            "- Reading position is now restored correctly after layout changes.\n"
            "- Chapter page counts work across multi-file chapters.\n"
            "- Leaving a book is much faster, even with large reading histories.");
}

TEST(ReleaseNotesExcerpt, GeneratedNotesLoseTheAuthorAndPullRequestTail) {
  EXPECT_EQ(excerptOf(NOTES_2_36, false),
            "A couple of minor fixes reported, most annoying probably the X4 ghosting on the settings screen\n"
            "- fix(home): refresh recent-book metadata when its .opf sidecar changes\n"
            "- fix(browser): label and trim the firmware picker's Options menu\n"
            "- fix(nav): front Up wraps from the first row of a list that opens with a header");
}

TEST(ReleaseNotesExcerpt, HeadingsAndCodeMarksAreLeftOut) {
  EXPECT_EQ(excerptOf(NOTES_2_35, false),
            "Changes since 2.31 (ed9b24d) through f046aa7.\n"
            "- fix: bound the per-chapter style memos -- a PDF-derived chapter has one unique inline style per word "
            "(703905f)\n"
            "- fix: stop rendering text that CSS makes invisible -- transparent colour, opacity 0, visibility hidden "
            "(f6e7dde)\n"
            "- docs: record the displayWindow capability gap and framebuffer baseline findings (90ff639)");
}

TEST(ReleaseNotesExcerpt, BoldAndLinksBecomePlainText) {
  EXPECT_EQ(excerptOf("**Bold** and [the docs](https://example.com/a) here"), "Bold and the docs here");
}

TEST(ReleaseNotesExcerpt, ABracketThatIsNoLinkStaysText) {
  EXPECT_EQ(excerptOf("array[0] is [not a link"), "array[0] is [not a link");
}

TEST(ReleaseNotesExcerpt, EveryBulletBecomesADash) {
  EXPECT_EQ(excerptOf("* star\n+ plus\n  - nested"), "- star\n- plus\n- nested");
}

TEST(ReleaseNotesExcerpt, RulesAndTheFullChangelogLineAreLeftOut) {
  EXPECT_EQ(excerptOf("Intro\n\n---\n\n**Full Changelog**: https://github.com/o/r/compare/2.36...2.37"), "Intro");
}

TEST(ReleaseNotesExcerpt, NotesWithNothingButChromeGiveNothing) {
  EXPECT_EQ(excerptOf("## What's Changed\r\n\r\n**Full Changelog**: https://github.com/o/r/compare/a...b"), "");
  EXPECT_EQ(excerptOf(""), "");
}

TEST(ReleaseNotesExcerpt, StopsAfterMaxLines) { EXPECT_EQ(excerptOf("a\nb\nc\nd\ne"), "a\nb\nc\nd"); }

TEST(ReleaseNotesExcerpt, TheCutLastLineOfAPrefixIsLeftOut) {
  EXPECT_EQ(excerptOf("First\nSecond\nThird is cut sh", false), "First\nSecond");
  EXPECT_EQ(excerptOf("No line has ended yet", false), "");
}

TEST(ReleaseNotesExcerpt, TheLastLineOfACompleteBodyIsKept) { EXPECT_EQ(excerptOf("First\nLast"), "First\nLast"); }

TEST(ReleaseNotesExcerpt, ALineThatDoesNotFitEndsAtAWordAndAnEllipsis) {
  // 15 bytes of room: "Short\n" leaves 9, of which the ellipsis takes 3.
  EXPECT_EQ(excerptOf("Short\nThis line is far too long", true, 16), "Short\nThis\xE2\x80\xA6");
}

TEST(ReleaseNotesExcerpt, TheEllipsisNeverSplitsACodepoint) {
  // 10 bytes of room: 7 for text before the ellipsis, which would cut the fourth two-byte e-acute in half.
  EXPECT_EQ(excerptOf("\xC3\xA9\xC3\xA9\xC3\xA9\xC3\xA9\xC3\xA9\xC3\xA9", true, 11),
            "\xC3\xA9\xC3\xA9\xC3\xA9\xE2\x80\xA6");
}

}  // namespace
